// TODO extract every single list into this file instead so it can later be fed into the search function

export const sizeTokens = [
  { token: '--space-xxs', size: '4px', name: 'XXS space ' },
  { token: '--space-xs', size: '8px', name: 'XS space ' },
  { token: '--space-s', size: '12px', name: 'S space ' },
  { token: '--space-m', size: '18px', name: 'M space ' },
  { token: '--space-l', size: '24px', name: 'L space ' },
  { token: '--space-xl', size: '34px', name: 'XL space ' },
  { token: '--space-xxl', size: '48px', name: 'XXL space ' },
  { token: '--space-xxxl', size: '64px', name: 'XXXL space ' },
]

export const fontSizeTokens = [
  { name: 'XXS size', token: '--font-size-xxs', size: '1rem' },
  { name: 'XS size', token: '--font-size-xs', size: '1.15rem' },
  { name: 'S size', token: '--font-size-s', size: '1.3rem' },
  { name: 'M size', token: '--font-size-m', size: '1.5rem' },
  { name: 'L size', token: '--font-size-l', size: '1.8rem' },
  { name: 'XL size', token: '--font-size-xl', size: '2rem' },
  { name: 'XXL size', token: '--font-size-xxl', size: '2.6rem' },
  { name: 'XXXL size', token: '--font-size-xxxl', size: '3.4rem' },
  { name: 'XXXXL size', token: '--font-size-xxxxl', size: '4.8rem' },
]

export const darkThemeTokens = [
  { name: 'Background', token: '--dark-color-bg', rgb: 'rgb(17, 17, 17)', hex: '#111111' },
  { name: 'Background Raised', token: '--dark-color-bg-raised', rgb: 'rgb(28, 28, 28)', hex: '#1C1C1C' },
  { name: 'Background Medium', token: '--dark-color-bg-medium', rgb: 'rgb(22, 22, 22)', hex: '#161616' },
  { name: 'Background Lowered', token: '--dark-color-bg-lowered', rgb: 'rgb(12, 12, 12)', hex: '#0C0C0C' },
  { name: 'Text', token: '--dark-color-text', rgb: 'rgb(231, 231, 231)', hex: '#E7E7E7' },
  { name: 'Text Light', token: '--dark-color-text-light', rgb: 'rgb(180, 180, 180)', hex: '#B4B4B4' },
  { name: 'Text Lighter', token: '--dark-color-text-lighter', rgb: 'rgb(90, 90, 90)', hex: '#5A5A5A' },
  { name: 'Text Lightest', token: '--dark-color-text-lightest', rgb: 'rgb(65, 65, 65)', hex: '#414141' },
  { name: 'Text Invert', token: '--dark-color-text-invert', rgb: 'rgb(17, 17, 17)', hex: '#111111' },
  { name: 'Button Gray', token: '--dark-color-button-gray', rgb: 'rgb(46, 46, 46)', hex: '#2E2E2E' },
  { name: 'Button Gray Hover', token: '--dark-color-button-gray-hover', rgb: 'rgb(38, 38, 38)', hex: '#262626' },
  { name: 'Button Fill', token: '--dark-color-button-fill', rgb: 'rgb(250, 250, 250)', hex: '#FAFAFA' },
  { name: 'Button Fill Hover', token: '--dark-color-button-fill-hover', rgb: 'rgb(210, 210, 210)', hex: '#D2D2D2' },
  { name: 'Text Red', token: '--dark-color-text-red', rgb: 'rgb(243, 78, 70)', hex: '#F34E46' },
  { name: 'Background Red Lowered', token: '--dark-color-bg-red-lowered', rgb: 'rgb(104, 24, 24)', hex: '#681818' },
  { name: 'Background Red Raised', token: '--dark-color-bg-red-raised', rgb: 'rgb(127, 29, 29)', hex: '#7F1D1D' },
  { name: 'Text Green', token: '--dark-color-text-green', rgb: 'rgb(106, 207, 48)', hex: '#6ACF30' },
  { name: 'Background Green Lowered', token: '--dark-color-bg-green-lowered', rgb: 'rgb(40, 95, 8)', hex: '#285F08' },
  { name: 'Background Green Raised', token: '--dark-color-bg-green-raised', rgb: 'rgb(26, 122, 13)', hex: '#1A7A0D' },
  { name: 'Text Yellow', token: '--dark-color-text-yellow', rgb: 'rgb(255, 193, 7)', hex: '#FFC107' },
  { name: 'Background Yellow Lowered', token: '--dark-color-bg-yellow-lowered', rgb: 'rgb(78, 52, 0)', hex: '#4E3400' },
  { name: 'Background Yellow Raised', token: '--dark-color-bg-yellow-raised', rgb: 'rgb(152, 104, 0)', hex: '#986800' },
  { name: 'Text Blue', token: '--dark-color-text-blue', rgb: 'rgb(85, 141, 245)', hex: '#558DF5' },
  { name: 'Background Blue Lowered', token: '--dark-color-bg-blue-lowered', rgb: 'rgb(13, 32, 74)', hex: '#0D204A' },
  { name: 'Background Blue Raised', token: '--dark-color-bg-blue-raised', rgb: 'rgb(26, 59, 119)', hex: '#1A3B77' },
  { name: 'Border', token: '--dark-color-border', rgb: 'rgb(40, 40, 40)', hex: '#282828' },
  { name: 'Border Strong', token: '--dark-color-border-strong', rgb: 'rgb(54, 54, 54)', hex: '#363636' },
  { name: 'Border Weak', token: '--dark-color-border-weak', rgb: 'rgb(36, 36, 36)', hex: '#242424' },
  { name: 'Accent', token: '--dark-color-accent', rgb: 'rgb(193, 118, 255)', hex: '#C176FF' },
  { name: 'Background Accent Raised', token: '--dark-color-bg-accent-raised', rgb: 'Inferred from the accent color. 40% darker', hex: null },
  { name: 'Background Accent Lowered', token: '--dark-color-bg-accent-lowered', rgb: 'Inferred from the accent color. 55% darker', hex: null },
]

export const lightThemeTokens = [
  { name: 'Background', token: '--light-color-bg', rgb: 'rgb(246, 246, 246)', hex: '#F6F6F6' },
  { name: 'Background Raised', token: '--light-color-bg-raised', rgb: 'rgb(222, 222, 222)', hex: '#DEDEDE' },
  { name: 'Background Medium', token: '--light-color-bg-medium', rgb: 'rgb(236, 236, 236)', hex: '#ECECEC' },
  { name: 'Background Lowered', token: '--light-color-bg-lowered', rgb: 'rgb(255, 255, 255)', hex: '#FFFFFF' },
  { name: 'Text', token: '--light-color-text', rgb: 'rgb(8, 8, 8)', hex: '#080808' },
  { name: 'Text Light', token: '--light-color-text-light', rgb: 'rgb(64, 64, 64)', hex: '#404040' },
  { name: 'Text Lighter', token: '--light-color-text-lighter', rgb: 'rgb(92, 92, 92)', hex: '#5C5C5C' },
  { name: 'Text Lightest', token: '--light-color-text-lightest', rgb: 'rgb(128, 128, 128)', hex: '#808080' },
  { name: 'Text Invert', token: '--light-color-text-invert', rgb: 'rgb(248, 248, 248)', hex: '#F8F8F8' },
  { name: 'Button Gray', token: '--light-color-button-gray', rgb: 'rgb(224, 224, 224)', hex: '#E0E0E0' },
  { name: 'Button Gray Hover', token: '--light-color-button-gray-hover', rgb: 'rgb(198, 198, 198)', hex: '#C6C6C6' },
  { name: 'Button Fill', token: '--light-color-button-fill', rgb: 'rgb(12, 12, 12)', hex: '#0C0C0C' },
  { name: 'Button Fill Hover', token: '--light-color-button-fill-hover', rgb: 'rgb(52, 52, 52)', hex: '#343434' },
  { name: 'Text Red', token: '--light-color-text-red', rgb: 'rgb(209, 60, 52)', hex: '#D13C34' },
  { name: 'Background Red Lowered', token: '--light-color-bg-red-lowered', rgb: 'rgb(172, 45, 45)', hex: '#AC2D2D' },
  { name: 'Background Red Raised', token: '--light-color-bg-red-raised', rgb: 'rgb(220, 38, 38)', hex: '#DC2626' },
  { name: 'Text Green', token: '--light-color-text-green', rgb: 'rgb(77, 160, 29)', hex: '#4DA01D' },
  { name: 'Background Green Lowered', token: '--light-color-bg-green-lowered', rgb: 'rgb(42, 114, 19)', hex: '#2A7213' },
  { name: 'Background Green Raised', token: '--light-color-bg-green-raised', rgb: 'rgb(61, 146, 35)', hex: '#3D9223' },
  { name: 'Text Yellow', token: '--light-color-text-yellow', rgb: 'rgb(176, 129, 15)', hex: '#B0810F' },
  { name: 'Background Yellow Lowered', token: '--light-color-bg-yellow-lowered', rgb: 'rgb(230, 205, 137)', hex: '#E6CD89' },
  { name: 'Background Yellow Raised', token: '--light-color-bg-yellow-raised', rgb: 'rgb(253, 200, 86)', hex: '#FDC856' },
  { name: 'Text Blue', token: '--light-color-text-blue', rgb: 'rgb(85, 141, 245)', hex: '#558DF5' },
  { name: 'Background Blue Lowered', token: '--light-color-bg-blue-lowered', rgb: 'rgb(196, 214, 255)', hex: '#C4D6FF' },
  { name: 'Background Blue Raised', token: '--light-color-bg-blue-raised', rgb: 'rgb(136, 178, 255)', hex: '#88B2FF' },
  { name: 'Border', token: '--light-color-border', rgb: 'rgb(200, 200, 200)', hex: '#C8C8C8' },
  { name: 'Border Strong', token: '--light-color-border-strong', rgb: 'rgb(152, 152, 152)', hex: '#989898' },
  { name: 'Border Weak', token: '--light-color-border-weak', rgb: 'rgb(224, 224, 224)', hex: '#E0E0E0' },
  { name: 'Accent', token: '--light-color-accent', rgb: 'rgb(193, 118, 255)', hex: '#C176FF' },
  { name: 'Background Accent Raised', token: '--light-color-bg-accent-raised', rgb: 'Inferred from the accent color. 25% darker', hex: null },
  { name: 'Background Accent Lowered', token: '--light-color-bg-accent-lowered', rgb: 'Inferred from the accent color. 40% darker', hex: null },
]

export const componentList = [
  { name: 'Accordion', path: '/docs/components/accordion', tags: ['group'], description: 'Expandable content sections that can be toggled open and closed', disabled: false },
  { name: 'Accordion Group', path: '/docs/components/accordion-group', tags: ['group'], description: 'Group of accordions that can be toggled open and closed individually or each at a time', disabled: false },
  { name: 'Alert', path: '/docs/components/alert', description: 'Displays important messages or notifications to users', disabled: false },
  { name: 'Avatar', path: '/docs/components/avatar', description: 'Circular image component for user profiles or icons', disabled: false },
  { name: 'Badge', path: '/docs/components/badge', description: 'Small visual indicator for status, counts, or labels', disabled: false },
  { name: 'Breadcrumbs', path: '/docs/components/breadcrumbs', tags: ['item'], description: 'Navigation aid showing current page location in hierarchy', disabled: true },
  { name: 'Button', path: '/docs/components/button', tags: ['group'], description: 'Interactive element for triggering actions or events', disabled: true },
  { name: 'Calendar', path: '/docs/components/calendar', tags: ['date', 'picker'], description: 'Date selection and display component with month view', disabled: true },
  { name: 'Card', path: '/docs/components/card', description: 'Container component for grouping related content', disabled: true },
  { name: 'Checkbox', path: '/docs/components/checkbox', description: 'Binary input control for selecting multiple options', disabled: true },
  { name: 'Copy Clipboard', path: '/docs/components/copy-clipboard', description: 'Button that copies text to clipboard with feedback', disabled: true },
  { name: 'Divider', path: '/docs/components/divider', description: 'Visual separator between content sections', disabled: true },
  { name: 'Drawer', path: '/docs/components/drawer', description: 'Sliding panel that appears from screen edges', disabled: true },
  { name: 'Dropdown', path: '/docs/components/dropdown', tags: ['item', 'title'], description: 'Menu that appears when clicking a trigger element', disabled: true },
  { name: 'Flex', path: '/docs/components/flex', description: 'Flexbox-based layout component for one-dimensional layouts', disabled: true },
  { name: 'Grid', path: '/docs/components/grid', description: 'Grid-based layout component for two-dimensional layouts', disabled: true },
  { name: 'Input', path: '/docs/components/input', tags: ['input', 'color', 'counter', 'dropzone', 'file', 'password', 'textarea'], description: 'Text input field with various types and features', disabled: true },
  { name: 'Kbd', path: '/docs/components/kbd', tags: ['group'], description: 'Keyboard key visualization component', disabled: true },
  { name: 'Modal', path: '/docs/components/modal', description: 'Dialog box that appears on top of main content', disabled: true },
  { name: 'OTP', path: '/docs/components/otp', tags: ['group'], description: 'One-time password input with multiple fields', disabled: true },
  { name: 'Pagination', path: '/docs/components/pagination', description: 'Navigation for splitting content into pages', disabled: true },
  { name: 'Popout', path: '/docs/components/popout', description: 'Floating element that appears relative to a trigger', disabled: true },
  { name: 'Progress', path: '/docs/components/progress', description: 'Visual indicator for task completion or loading state', disabled: true },
  { name: 'Radio', path: '/docs/components/radio', tags: ['group'], description: 'Input control for selecting a single option', disabled: true },
  { name: 'Select', path: '/docs/components/select', description: 'Dropdown for selecting from a list of options', disabled: true },
  { name: 'Sheet', path: '/docs/components/sheet', description: 'Bottom sheet that slides up from screen bottom', disabled: true },
  { name: 'Sidebar', path: '/docs/components/sidebar', description: 'Vertical navigation panel typically on screen edges', disabled: true },
  { name: 'Skeleton', path: '/docs/components/skeleton', description: 'Loading placeholder that mimics content structure', disabled: true },
  { name: 'Spinner', path: '/docs/components/spinner', description: 'Animated loading indicator', disabled: true },
  { name: 'Switch', path: '/docs/components/switch', description: 'Toggle switch for binary options', disabled: true },
  { name: 'Table', path: '/docs/components/table', tags: ['cell', 'head', 'header', 'row', 'select'], description: 'Data display component with rows and columns', disabled: true },
  { name: 'Tabs', path: '/docs/components/tabs', tags: ['group'], description: 'Container for organizing content into tabbed sections', disabled: true },
  { name: 'Tab', path: '/docs/components/tab', tags: ['tabs'], description: 'Individual tab within a tabbed interface', disabled: true },
  { name: 'Toast', path: '/docs/components/toast', description: 'Temporary notification message that appears and disappears', disabled: true },
  { name: 'Tooltip', path: '/docs/components/tooltip', description: 'Small popup that appears when hovering over an element', disabled: true },
]

export const lineHeightTokens = [
  { name: 'Tight', token: '--line-height-tight', height: '1.125em' },
  { name: 'Title', token: '--line-height-title', height: '1.25em' },
  { name: 'Base', token: '--line-height-base', height: '1.4em' },
]

export const fontWeightTokens = [
  { name: 'Light', token: '--font-weight-light', weight: '300' },
  { name: 'Regular', token: '--font-weight', weight: '400' },
  { name: 'Medium', token: '--font-weight-medium', weight: '500' },
  { name: 'Semibold', token: '--font-weight-semibold', weight: '600' },
  { name: 'Bold', token: '--font-weight-bold', weight: '700' },
  { name: 'Extrabold', token: '--font-weight-extrabold', weight: '800' },
  { name: 'Black', token: '--font-weight-black', weight: '900' },
]

export const zIndexTokens = [
  { name: 'Behind', token: '--z-behind', value: '-1', description: 'Used for elements that should appear behind other content' },
  { name: 'Default', token: '--z-default', value: '1', description: 'Base z-index for standard page elements' },
  { name: 'Active', token: '--z-active', value: '50', description: 'For elements that are currently being interacted with' },
  { name: 'Mask', token: '--z-mask', value: '75', description: 'Used for semi-transparent overlays that block interaction' },
  { name: 'Sticky', token: '--z-sticky', value: '100', description: 'For elements that stick to viewport while scrolling' },
  { name: 'Nav', token: '--z-nav', value: '200', description: 'Navigation elements that should stay above content' },
  { name: 'Overlay', token: '--z-overlay', value: '300', description: 'Full-screen overlays that cover the entire viewport' },
  { name: 'Popout', token: '--z-popout', value: '400', description: 'Floating elements like dropdowns and tooltips' },
  { name: 'Toast', token: '--z-toast', value: '500', description: 'Temporary notifications that appear above other UI' },
  { name: 'Modal', token: '--z-modal', value: '600', description: 'Dialog boxes that require user attention' },
]

export const transitionTokens = [
  { name: 'Fast', token: '--transition-fast', value: '0.0625s all ease-in-out', description: 'Used for interactive element hover states' },
  { name: 'Default', token: '--transition', value: '0.125s all cubic-bezier(0.65, 0, 0.35, 1)', description: 'Used for appear animations of display elements' },
  { name: 'Slow', token: '--transition-slow', value: '0.25s all cubic-bezier(0.65, 0, 0.35, 1)', description: 'Slower transitions for large elements' },
]
