export const componentList = [
  { name: 'Accordion', path: '/docs/components/accordion', tags: ['group'], description: 'Expandable content sections that can be toggled open and closed' },
  { name: 'Alert', path: '/docs/components/alert', description: 'Displays important messages or notifications to users' },
  { name: 'Avatar', path: '/docs/components/avatar', description: 'Circular image component for user profiles or icons' },
  { name: 'Badge', path: '/docs/components/badge', description: 'Small visual indicator for status, counts, or labels' },
  { name: 'Breadcrumbs', path: '/docs/components/breadcrumbs', tags: ['item'], description: 'Navigation aid showing current page location in hierarchy' },
  { name: 'Button', path: '/docs/components/button', tags: ['group'], description: 'Interactive element for triggering actions or events' },
  { name: 'Calendar', path: '/docs/components/calendar', tags: ['date', 'picker'], description: 'Date selection and display component with month view' },
  { name: 'Card', path: '/docs/components/card', description: 'Container component for grouping related content' },
  { name: 'Checkbox', path: '/docs/components/checkbox', description: 'Binary input control for selecting multiple options' },
  { name: 'Copy Clipboard', path: '/docs/components/copy-clipboard', description: 'Button that copies text to clipboard with feedback' },
  { name: 'Divider', path: '/docs/components/divider', description: 'Visual separator between content sections' },
  { name: 'Drawer', path: '/docs/components/drawer', description: 'Sliding panel that appears from screen edges' },
  { name: 'Dropdown', path: '/docs/components/dropdown', tags: ['item', 'title'], description: 'Menu that appears when clicking a trigger element' },
  { name: 'Flex', path: '/docs/components/flex', description: 'Flexbox-based layout component for one-dimensional layouts' },
  { name: 'Grid', path: '/docs/components/grid', description: 'Grid-based layout component for two-dimensional layouts' },
  { name: 'Input', path: '/docs/components/input', tags: ['input', 'color', 'counter', 'dropzone', 'file', 'password', 'textarea'], description: 'Text input field with various types and features' },
  { name: 'Kbd', path: '/docs/components/kbd', tags: ['group'], description: 'Keyboard key visualization component' },
  { name: 'Modal', path: '/docs/components/modal', description: 'Dialog box that appears on top of main content' },
  { name: 'OTP', path: '/docs/components/otp', tags: ['group'], description: 'One-time password input with multiple fields' },
  { name: 'Pagination', path: '/docs/components/pagination', description: 'Navigation for splitting content into pages' },
  { name: 'Popout', path: '/docs/components/popout', description: 'Floating element that appears relative to a trigger' },
  { name: 'Progress', path: '/docs/components/progress', description: 'Visual indicator for task completion or loading state' },
  { name: 'Radio', path: '/docs/components/radio', tags: ['group'], description: 'Input control for selecting a single option' },
  { name: 'Select', path: '/docs/components/select', description: 'Dropdown for selecting from a list of options' },
  { name: 'Sheet', path: '/docs/components/sheet', description: 'Bottom sheet that slides up from screen bottom' },
  { name: 'Sidebar', path: '/docs/components/sidebar', description: 'Vertical navigation panel typically on screen edges' },
  { name: 'Skeleton', path: '/docs/components/skeleton', description: 'Loading placeholder that mimics content structure' },
  { name: 'Spinner', path: '/docs/components/spinner', description: 'Animated loading indicator' },
  { name: 'Switch', path: '/docs/components/switch', description: 'Toggle switch for binary options' },
  { name: 'Table', path: '/docs/components/table', tags: ['cell', 'head', 'header', 'row', 'select'], description: 'Data display component with rows and columns' },
  { name: 'Tab', path: '/docs/components/tab', tags: ['tabs'], description: 'Individual tab within a tabbed interface' },
  { name: 'Tabs', path: '/docs/components/tabs', tags: ['group'], description: 'Container for organizing content into tabbed sections' },
  { name: 'Toast', path: '/docs/components/toast', description: 'Temporary notification message that appears and disappears' },
  { name: 'Tooltip', path: '/docs/components/tooltip', description: 'Small popup that appears when hovering over an element' },
]