export const testData = [
  {
    ruleId: 'iam-policy-002',
    title: 'IAM Policy Not in Use',
    description: 'An Identity Access and Management (IAM) policy has been identified as not in use. Unused IAM policies increase management complexity and create a larger surface for potential security exploits. These risks can be mitigated by deleting unused IAM policies.',
    provider: 'aws',
    account: '999192891411',
    region: 'ap-northeast-1',
    resourceId: 'AWSLambdaBasicExecutionRole-c09bd8da-bd03-4ff1-8b65-69c1b49e1268',
    passed: false,
    suppressionId: null,
    violationId: 358358531,
    tags: '',
  },
  {
    ruleId: 'iam-policy-002',
    title: 'IAM Policy Not in Use',
    description: 'An Identity Access and Management (IAM) policy has been identified as not in use. Unused IAM policies increase management complexity and create a larger surface for potential security exploits. These risks can be mitigated by deleting unused IAM policies.',
    provider: 'aws',
    account: '999192891411',
    region: 'ap-northeast-1',
    resourceId: 'test',
    passed: false,
    suppressionId: null,
    violationId: 358358532,
    tags: '',
  },
  {
    ruleId: 'iam-policy-002',
    title: 'IAM Policy Not in Use',
    description: 'An Identity Access and Management (IAM) policy has been identified as not in use. Unused IAM policies increase management complexity and create a larger surface for potential security exploits. These risks can be mitigated by deleting unused IAM policies.',
    provider: 'aws',
    account: '999192891411',
    region: 'ap-northeast-1',
    resourceId: 'asdrgdag',
    passed: false,
    suppressionId: null,
    violationId: 358358533,
    tags: '',
  },
  {
    ruleId: 'iam-policy-002',
    title: 'IAM Policy Not in Use',
    description: 'An Identity Access and Management (IAM) policy has been identified as not in use. Unused IAM policies increase management complexity and create a larger surface for potential security exploits. These risks can be mitigated by deleting unused IAM policies.',
    provider: 'aws',
    account: '999192891411',
    region: 'ap-northeast-1',
    resourceId: 'AWSLambdaBasicExecutionRole-84a5dbad-3b48-4186-ac9b-21eb9adb4263',
    passed: false,
    suppressionId: null,
    violationId: 358358534,
    tags: '',
  },
  {
    ruleId: 'iam-policy-002',
    title: 'IAM Policy Not in Use',
    description: 'An Identity Access and Management (IAM) policy has been identified as not in use. Unused IAM policies increase management complexity and create a larger surface for potential security exploits. These risks can be mitigated by deleting unused IAM policies.',
    provider: 'aws',
    account: '999192891411',
    region: 'ap-northeast-1',
    resourceId: 'NCPInstanceAccess',
    passed: false,
    suppressionId: null,
    violationId: 358358535,
    tags: '',
  },
  {
    ruleId: 'iam-policy-002',
    title: 'IAM Policy Not in Use',
    description: 'An Identity Access and Management (IAM) policy has been identified as not in use. Unused IAM policies increase management complexity and create a larger surface for potential security exploits. These risks can be mitigated by deleting unused IAM policies.',
    provider: 'aws',
    account: '999192891411',
    region: 'ap-northeast-1',
    resourceId: 'customadminpolicy=',
    passed: false,
    suppressionId: null,
    violationId: 358358536,
    tags: '',
  },
  {
    ruleId: 'iam-policy-002',
    title: 'IAM Policy Not in Use',
    description: 'An Identity Access and Management (IAM) policy has been identified as not in use. Unused IAM policies increase management complexity and create a larger surface for potential security exploits. These risks can be mitigated by deleting unused IAM policies.',
    provider: 'aws',
    account: '999192891411',
    region: 'ap-northeast-2',
    resourceId: 'NCPInstanceAccess',
    passed: false,
    suppressionId: null,
    violationId: 358358537,
    tags: '',
  },
] as const
